version: '3.6'

services:
  crowdwork:
    container_name: crowdwork
    build: ./
    ports:
      - '3052:3000'
    volumes:
      - ./:/app
    working_dir: /app
    restart: always
    command: python run_task.py mephisto.blueprint.link_task_source=true +HYDRA_FULL_ERROR=1

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./db:/data/db
    restart: always
