version: '3.6'

services:
  crowdwork:
    container_name: crowdwork
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    restart: no
    command: bash -c "python run_task.py conf=config_inhouse mephisto.blueprint.link_task_source=true +HYDRA_FULL_ERROR=1"

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./db:/data/db
    restart: always

  json_server:
    build: ./json_server
    ports:
      - "8008:8008"
    depends_on:
      - mongo
      - crowdwork
    environment:
      - FLASK_ENV=development
