version: '3.6'

services:
  crowdwork:
    container_name: crowdwork
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: 'python run_task.py mephisto.blueprint.link_task_source=true'
