version: '3.6'

services:
  crowdwork:
    container_name: crowdwork
    build: ./
    ports:
      - '3051:3051'
    volumes:
      - ./:/app
    working_dir: /app
    command: 'python run_task.py mephisto.architect.port=3051'
