#@package _global_
defaults:
  - /mephisto/blueprint: static_react_task
  - /mephisto/architect: local
  - /mephisto/provider: prolific
mephisto:
  blueprint:
    task_source: ${task_dir}/webapp/build/bundle.js
    data_csv: ${task_dir}/texts.csv
    link_task_source: false
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 2
    onboarding_qualification: test-react-static-qualification
  log_level: 'debug'
  task:
    task_name: 'crowdwork'
    task_title: 'Identifing conspiracy teories [test device]'
    task_description: '1) classify texts as conspiracy theories and 2) identify specific narrative components of conspiracy theories in the text (called aspects).'
    task_reward: 30
    task_tags: 'test,simple,button'
    max_num_concurrent_units: 10
  provider:
    prolific_external_study_url: 'https://crowdwork.devmaxup.com/?participant_id={{%PROLIFIC_PID%}}&study_id={{%STUDY_ID%}}&submission_id={{%SESSION_ID%}}'
    prolific_id_option: 'url_parameters'
    prolific_workspace_name: 'prospection lab'
    prolific_project_name: 'test'
    prolific_estimated_completion_time_in_minutes: 1
    prolific_allow_list_group_name: 'Test'
    # prolific_device_compatibility: ["desktop"]
    # prolific_block_list_group_name: "Block list"
    prolific_eligibility_requirements:
      - name: 'CustomWhitelistEligibilityRequirement'
        white_list:
          - 658008ede2fa33549f8796a0
          - 658009104d87876ec6800314
          - 6580087140a25fafd8a9bdcf
          - 658008ae678be2d216a86929
          - 67486a26ac5e3ba3d070b532
