#@package _global_
defaults:
  - /mephisto/blueprint: static_react_task
  - /mephisto/architect: local
  - /mephisto/provider: inhouse
mephisto:
  blueprint:
    task_source: ${task_dir}/webapp/build/bundle.js
    data_csv: ${task_dir}/texts.csv
    link_task_source: true
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 1
    onboarding_qualification: test-react-static-qualification
  log_level: "debug"
  provider:
    ui_base_url: "http://localhost:3000"
  task:
    task_name: "crowdwork"
    task_title: "Identifing conspiracy teories "
    task_description: "In this task you will 1) classify texts as conspiracy theories and 2) identify specific narrative components of conspiracy theories in the text (called aspects)."
    task_reward: 0.05
    task_tags: "test,simple,button"
    # We expect to be able to handle 300 concurrent tasks without issue
    max_num_concurrent_units: 300
    force_rebuild: true
    submission_timeout: 12000
    assignment_duration_in_seconds: 12000